### ISSUE TITLE
Proposal: naming convention to harmonize configuration's variables

### ISSUE THREAD

**Issue by edouard-lopez** [rafaelrinaldi/pure#130]
**related:** #74, e5af49f

---

While [revamping the README.md](https://github.com/rafaelrinaldi/pure/pull/127/commits/e5af49f83ba26cd3b0af390696a79c86e70b5483) I realized we have some inconsistencies in the naming of variables. This would be nice to improve that before releasing `2.0.0` as it will be a breaking change.

## Global Globa Variable

> Base colors should follow `$pure_color_<meaning>` pattern (cf. [bootstrap naming](https://getbootstrap.com/docs/4.1/utilities/colors/)).

##### Example

```fish
$pure_color_info     # cyan
$pure_color_success  # green
$pure_color_warning  # yellow
$pure_color_danger   # red
$pure_color_light
$pure_color_dark
$pure_color_muted    # gray
```

## Feature's Variables

> Each feature should have a dedicated variables to allow customization.

> Feature's variables (flag, symbol, color) should use `$pure_<type>_<feature>` naming pattern:
>
> | Role   | Name pattern             |
> | :----- | :----------------------- |
> | flag   | `$pure_<verb>_<feature>` |
> | color  | `$pure_color_<feature>`  |
> | symbol | `$pure_symbol_<feature>` |

##### Example

```fish
$pure_enable_git_status
```

```fish
$pure_symbol_git_unpushed_commits
```

```fish
$pure_color_git_unpulled_commits
```

## Feature Flag's Variable

> Name should follow `$pure_<verb>_<feature>` pattern, where:
  > * `verb` describe the action triggered by the feature (_i.e._ `separate`, `begin`, `show`, etc.) ;
  > * `feature` descibre the _what_ of the feature (_i.e._ `prompt_on_error`, `with_current_directory`, `git_status`, etc.).

> Value should be **a boolean**.
  
##### Example

```fish
$pure_begin_prompt_with_current_directory = true
```

```fish
$pure_enable_git_async = false
```

## Avoid abbreviation

> Use complete word over abbreviation.

##### Example

```fish
$pure_threshold_command_duration
```

**Comment by schrodincat** [comment]
Excellent proposal!
I’m not sure about changing `pure_color_ELEMENT` to `pure_ELEMENT_color` while using `pure_color_MEANING` though.

I think it would be more consistent if we would stick with one approach. Either (which I personally prefer):
`pure_color_ELEMENT`, `pure_symbol_ELEMENT`, `pure_color_MEANING`

or:
`pure_ELEMENT_color`, `pure_ELEMENT_symbol`, `pure_MEANING_color`

**Comment by edouard-lopez** [comment]
If you stick to your second proposal it's indeed better to have `pure_success_color` instead of `pure_color_success`, for consistency.

Depending on the content of a file, only variables related to one feature vs. mix of feature/global variable, I reckon both conventions have pros/cons. In the former, prepending the feature name will be annoying, on the latter case it could help prevent confusion.

@rafaelrinaldi @faho @jorgebucaran feedback?

**Comment by schrodincat** [comment]
Since those are public variables to tweak prompt settings for the end user, I think we should prioritize clarity and simplicity. That’s debatable of course, but I feel like first variation is easier on the eyes.

But again, it’s not like there is a huge difference.

**Comment by rafaelrinaldi** [comment]
I really like this idea.

I'd like to share that I personally try to avoid shortening of words when naming things ("error" instead of "err", "command" instead of "cmd", etc) but I am open to make an exception if you feel strong about it.

**1. Global Variable**

One idea does not invalidate the other. We can have both.

**2. Feature Flag Variable**

I agree.

**3. Flag, Symbol and Color**

I agree with the structure you propose.

- Since this is a color, I believe we could drop `pure_cmd_max_exec_duration_color` altogether and just use `pure_color_danger` instead. I think for colors in general we can rely on the table of colors and avoid exposing feature-specific colors to the user because we want to ensure a minimum visual consistency so the theme looks great.
- I like `pure_cmd_max_exec_duration` but would prefer `pure_command_max_execution_time`.

**4. Specific Symbol Variable**

Is there any other place than the Git arrow variables that you can see this being useful? I see this makes things more flexible but I don't think it's necessary (I wouldn't style the arrow up different than the arrow down, etc). I think it's the case of letting this in a backlog and if users ask we can reconsider.

**5. Feature's Symbol Variable**

I disagree. I see "git" as a feature on its own rather than "symbol" and believe the current naming of variables for that is meaningful and easy to read.

**6. Feature symbol's color variable**

This goes back to the second item on the list I brought of on item 3.

**Comment by jorgebucaran** [comment]
Agree with 1 and 2. I am not sure about 5. I actually prefer the current `pure_symbol_git_arrow_down`. My trick: change `_` to a `.` in your mind and think of object hierarchies:

```console
pure.symbols.git_arrow_down
```

Above all, agree with this comment by @schrodincat: 

> Since those are public variables to tweak prompt settings for the end user, I think we should prioritize clarity and simplicity.

A consistent rule is better than no rule, so find out what makes sense to you and stick to it—good luck!

**Comment by schrodincat** [comment]
@rafaelrinaldi
1. I see no reason to have both `pure_color_red` and `pure_color_danger`, since they would have essentially the same values (that is if I understand you correctly).

3. I personally in favor of simplicity and consistency too. But the reason we’ve exposed color for every feature separately is that user asked for more customizations. I wouldn’t worry about visual consistency too much in this case though. We have defaults in `conf.d/pure.fish` and user can easily revert back to it if something ugly happens to born😅 I think we can mention of how hierarchy of settings is working in README and say that changing global color settings is preferable compared to tinkering color of separate feature for visual consistency sake.

4. I think we are only missing separate color variables for down and up arrows by this point. I’d add them just for consistency sake. I personally wouldn’t use it, but I can imagine someone would.

**Comment by rafaelrinaldi** [comment]
@schrodincat 

[1] I see it as a two-level abstraction, one more high level with the actual colors (full available colors) and the other with their context (danger, success, etc). For instance, red could be used for "danger" and some other state at the same time. But this can become confusing indeed. The reason I prefer keeping the actual colors instead of context-specific is because this is a terminal prompt (as opposed to a web app, in which case I'd pick the latter), so whoever wants to hack on the code would already be familiar with what's happening (I've customized many Vim themes over the years and most of them use straight up color names).

[3] Good point; I'm okay with that. I agree we could better explain how to approach theming in our README.

[4] Copy that.

**Comment by edouard-lopez** [comment]
I will make a serie of post so we can **upvote/downvote them**

---

@rafaelrinaldi

> I disagree. I see "git" as a feature on its own rather than "symbol" and believe the current naming of variables for that is meaningful and easy to read.

Current variable naming describe the symbol, not what it mean (unpulled/unpushed commit). Do you think this would work better:

    $pure_symbol_git_unpushed_commits   instead of $pure_symbol_git_arrow_up
    $pure_symbol_git_unpulled_commits

This give us have good readability and let user use `←` and `→` without being confused.

**Comment by edouard-lopez** [comment]
So we stick to `pure_symbol_<feature>`

---

@jorgebucaran

> Agree with 1 and 2. I am not sure about 5. I actually prefer the current pure_symbol_git_arrow_down

Instead of an object hierarchy I prefer to think in term of features, it's easier to refactor and work with all variable for a feature. Then we got something that 

    $pure.git.dirty.symbol
    $pure.git.unpushed_commits.symbol
    $pure.git.unpulled_commits.symbol

But this don't happen a lot and `$pure_symbol_git_unpushed_commits` spark something that `$pure_git_unpushed_commits_symbol` don't.

**Comment by edouard-lopez** [comment]
#### Global Variable:

Drop `$pure_color_<color>` in favor of `$pure_color_<meaning>` (_i.e._ `$pure_color_danger`).

**Comment by edouard-lopez** [comment]
#### Feature flag

`$pure_<verb>_<feature>` (_e.g._ `$pure_enable_git_async`).

**Comment by schrodincat** [comment]
> #### Specific Symbol Variable:
> Two variables for git unpulled/unpushed arrows color is overzealous, let's stick to a single one (split if user request it).

There is another argument in favour of using different color variables for git unpulled/unpushed arrows:  splitting would require to change user customisation variables and I'd say we should try not to introduce breaking changes after 2.0.0.

**Comment by edouard-lopez** [comment]
see PR #134
