### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by rafaelrinaldi** [rafaelrinaldi/pure#35]
Starting this issue to discuss best approaches to test fish code.

Some of the things I would love to test:

- Prompt features (symbols, order of how things are rendered, etc)
- Git integration (dirty branches, active branch, etc)
- Prompt consistency across different OS
- Speed (new implementation vs. "production" one, make sure there's no regressions were introduced)

Would love to hear from everybody, specially amazing people who have contributed to this project before @edouard-lopez, @oranja and @Shougo.

**Comment by Shougo** [comment]
It is good to add the tests.
I don't know the best approach to test fish code though.

**Comment by edouard-lopez** [comment]
I did [some tests](https://github.com/edouard-lopez/fish-ssh-agent-1) using [fishtape](https://github.com/fisherman/fishtape) it's pretty straight-forward to setup. However, I'm not sure everything will be worth  testing if we considering the cost to do it. IMHO, 
* [x] prompt: unit test, so OK ;
* [x] git integration: sounds like integration tests as it require `git` context ;
* [ ] consistency between OSes won't be automated or require VM so huge context.
* [ ] speed: could be unit tests, but otherwise what should we test? 

If we spent too much time writing tests with low utility for users, I reckon we are missing the point.

**Comment by rafaelrinaldi** [comment]
@edouard-lopez Great feedback. Yeah, I agree with what you said, I was just throwing some ideas out.

I think testing prompt and speed are the most important ones here. And what I mean by speed is to simply run a little benchmark from the current implementation and a release candidate to see if we're not doing anything crazy that's affecting processing in a negative way. It's very important that `pure` is as fast as it can be.

**Comment by pierrebeaucamp** [comment]
I would love to help out with this issue, but could you provide a bit more details regarding:

1. where you want those tests to run? Do you have a preferred CI service like Travis CI or Circle CI?
2. How would you tests the performance? Measure the time for cd'ing into git directories? What else would be worth testing?

I would set up some integration tests on my fork and open an PR once I'm satisfied with the results

**Comment by edouard-lopez** [comment]
@pierrebeaucamp 

For CI, I use Travis as it's pretty simple to setup, still I'm open to alternative. 

I think it's relevant to run the test in a container as we want a controlled environment with minimum configuration pollution. I would suggest to go for a docker as we [already used it for some tests](https://github.com/rafaelrinaldi/pure/issues/26#issuecomment-210014662), maybe creating our own docker image.

For the performance, do we have use-cases or is just for the sake of it? Without real issue, it will be premature optimization.

**Comment by pierrebeaucamp** [comment]
Travis & docker sound good to me.

My primary use case for analyzing performance is the time it takes to change directories, especially git directories. I'm coming from zsh, where there was no overhead at all of painting the prompt (as all the git commands were performed asynchronously). Ever since switching to fish, I miss the responsiveness of just navigating around.

It's easy enough the measure this by
```
git clone somerepo
cd somerepo
echo $CMD_DURATION
```

**Comment by edouard-lopez** [comment]
@pierrebeaucamp I reckon the asynchronous version has been added in the past 1-2 years as it wasn't present when I was using `zsh` more intensively.

So that's something we need to work on.

**Comment by rafaelrinaldi** [comment]
Thank you @pierrebeaucamp for volunteering on this. I have already expressed that this is something that I personally value a lot as you can see on my comments above.

As long as you can work on top of our current Docker based approach and provide benchmarks, you can pretty much go crazy and do whatever you feel like it would fit the project better 👍 

Let us know if we can help with anything.

**Comment by edouard-lopez** [comment]
See [`tests/` directory](https://github.com/rafaelrinaldi/pure/tree/master/tests) and [`installer.md`](https://github.com/rafaelrinaldi/pure/blob/master/installer.md) to see how we do tests with [`fishtape`](https://github.com/fisherman/fishtape) and `docker`.

Closing as inactive for the last year and a half.
