### ISSUE TITLE
Missing argument while setting threshold in __format_time.fish

### ISSUE THREAD

**Issue by keithschulze** [rafaelrinaldi/pure#47]
I just updated `pure` using oh-my-fish and I'm getting the following error every time I open a new shell.

```
Array index out of bounds
~/.local/share/omf/themes/pure/__format_time.fish (line 7):   set -l threshold $argv[2]
                                                                                     ^
in function '__format_time'
        called on line 41 of file ~/.config/fish/functions/fish_prompt.fish
        with parameter list '5'

in command substitution
        called on line 39 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
        called on standard input

in command substitution
        called on standard input

test: Missing argument at index 2
```

Result of `omf doctor`:

```
❯ omf doctor
Oh My Fish version:   5
OS type:              Darwin
Fish version:         fish, version 2.4.0
Git version:          git version 2.12.0
Git core.autocrlf:    no
Your shell is ready to swim.
```

Any advice on what might be wrong? Thanks in advance.

**Comment by rafaelrinaldi** [comment]
@keithschulze Hey, thanks for the report. This is indeed an odd behavior, since it seems to be complaining about a variable that should be a default value set. Let me ask you two things:

1. Have you set a custom value for `pure_command_max_exec_time` by any chance?
2. Can you try to run the _dockerized_ version of the project and see if the error persists?

**Comment by keithschulze** [comment]
I can confirm that #48 fixes the issue. Upgrading to fish 2.5.0 also does. Thanks for your help.

**Comment by rafaelrinaldi** [comment]
@keithschulze Thank you for reporting and for using pure :v:
