### ISSUE TITLE
First line isn't rendered on Terminal.app open in macOS

### ISSUE THREAD

**Issue by schrodincat** [rafaelrinaldi/pure#67]
**related:** #68

---

Expected behaviour:
<img width="682" alt="screen shot 2018-04-14 at 14 27 07" src="https://user-images.githubusercontent.com/13354491/38767755-0b49f280-3ff0-11e8-8fe1-3b6863778153.png">
Actual behaviour:
<img width="682" alt="screen shot 2018-04-14 at 14 23 24" src="https://user-images.githubusercontent.com/13354491/38767758-13d9d6a4-3ff0-11e8-9803-26a7c23a8b31.png">

**Comment by dallagi** [comment]
I'd like to see this solved too, especially since it doesn't only happen when the window is opened, but it happens when the terminal is cleared using the CTRL-L shortcut (while explicitly calling the `clear` function works as expected for some reason).

A fix that worked on my local setup is to change the way the `pre_prompt` function is called.

Instead of calling it implicitly with an event handler ( `function pre_prompt --on-event fish_prompt`), it should be called explicitly at the beginning of the `fish_prompt` function, like this:

```
function fish_prompt
  pre_prompt
  # ...
```

I'm not sure if this is the best and idiomatic way to achieve the desired behavior, but if it's an accettable fix I can submit a PR (unless the devs want to patch it themselves directly).

**Comment by rafaelrinaldi** [comment]
@schrodincat Thanks a lot for working on that! I really appreciate it. I will have a look at it as soon as I have time.
